"""Regenerate ``docs/learn/unit-catalog.md`` from the bundled unit catalogue.

Reads ``src/duq/data/units.toml`` (via the installed package data) and resolves
each atom's dimension through the default registry, so the reference page always
mirrors what ``duq.unit(...)`` actually accepts.  Run from the repository root
inside the ``docs`` (or ``test-jax``) environment::

    pixi run -e docs python docs/gen_unit_catalog.py

The generated page is committed; keep it in sync after editing ``units.toml``.
"""

from __future__ import annotations

import importlib.resources
import tomllib
from pathlib import Path

import duq
from duq.analysis import name_of

_HEADER = """\
# Unit catalog

<!-- This page is generated by docs/gen_unit_catalog.py from
     src/duq/data/units.toml; do not edit by hand. -->

Every unit bundled with duq's default registry, grouped by physical dimension.
duq keeps a **small, curated** catalogue (pint/unyt/astropy ship far larger
ones); the trade-off buys JAX support, exact `Fraction` exponents and fail-loud
safety.  Any **prefixable** atom also accepts every SI prefix at parse time
(`km`, `MJ`, `ns`, …), so the prefixed forms are never listed separately.

Reach a unit with [`duq.unit("...")`][duq.unit], as an attribute on
[`duq.units`][duq.units] when its symbol is a valid identifier, or by
multiplying an array/number by it.
"""


def _rows() -> list[tuple[str, str, str, str, str, bool]]:
    resource = importlib.resources.files("duq.data").joinpath("units.toml")
    entries = tomllib.loads(resource.read_text(encoding="utf-8"))["units"]
    rows: list[tuple[str, str, str, str, str, bool]] = []
    for entry in entries.values():
        symbol = entry["symbol"]
        parsed = duq.unit(symbol)
        dim_name = name_of(parsed.dimension) or "other"
        rows.append(
            (
                dim_name,
                symbol,
                entry["name"],
                duq.dimension(dim_name).__str__() if dim_name != "other" else str(parsed.dimension),
                str(entry.get("scale", "1")),
                bool(entry.get("prefixable", False)),
            )
        )
    return rows


def main() -> None:
    """Write the grouped unit-catalog reference page."""
    rows = _rows()
    # Preserve the catalogue's curated order: group by dimension in first-seen order.
    order: list[str] = []
    groups: dict[str, list[tuple[str, str, str, str, str, bool]]] = {}
    for row in rows:
        dim = row[0]
        if dim not in groups:
            groups[dim] = []
            order.append(dim)
        groups[dim].append(row)

    lines = [_HEADER, ""]
    for dim in order:
        title = dim.replace("_", " ").capitalize()
        symbol = groups[dim][0][3]
        lines.append(f"## {title}  ·  `{symbol}`")
        lines.append("")
        lines.append("| Symbol | Name | Coherent-SI scale | Prefixable |")
        lines.append("|---|---|---|---|")
        for _dim, sym, name, _dimstr, scale, pref in groups[dim]:
            lines.append(f"| `{sym}` | {name} | {scale} | {'yes' if pref else 'no'} |")
        lines.append("")

    lines.append(f"_Total: {len(rows)} units across {len(order)} dimensions._")
    lines.append("")
    target = Path(__file__).with_name("learn") / "unit-catalog.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target} ({len(rows)} units, {len(order)} groups)")


if __name__ == "__main__":
    main()
