
name: formatting tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    format:
        name: Black
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
          - name: Install format dependencies
            run: python -m pip install black-nb shyaml
          - name: Run black-nb
            run: |
              black-nb -l 99 --check docs
