
name: code-style tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    format:
        name: Black
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
          - name: Install format dependencies
            run: |
              python -m pip install black-nb shyaml
              Python -m pip install black
          - name: Run black
            run: |
              black --check .
          - name: Run black-nb
            run: |
              black-nb --check .
          
